version: '3.7'

services:
  client:
    container_name: frontend
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '3005:3000'
    environment:
      - CHOKIDAR_USEPOLLING=true
